import java.io.File

plugins {
    kotlin("multiplatform") version "2.1.20"
}

group = "com.aikit"
version = "1.0.0"

repositories {
    mavenCentral()
}

// ---------------------------------------------------------------------------
// Embedded template codegen
// ---------------------------------------------------------------------------
// Kotlin/Native has no JVM-style classpath resources. We bake every file under
// `templates/` into a generated Kotlin source file so the binary carries the
// kit content with it. The generated file lives in build/generated/ and is
// added to commonMain — production code reads it via EmbeddedTemplates.files.
val templatesRoot: File = layout.projectDirectory.dir("templates").asFile
val generatedSrcDir: File = layout.buildDirectory.dir("generated/embeddedTemplates/kotlin").get().asFile

val generateEmbeddedTemplates by tasks.registering {
    val outputDir = generatedSrcDir
    val source = templatesRoot
    inputs.dir(source)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = File(outputDir, "com/aikit/setup/embedded")
        pkgDir.mkdirs()
        val out = File(pkgDir, "EmbeddedTemplates.kt")
        val files = source.walkTopDown()
            .filter { it.isFile }
            .toList()
            .sortedBy { it.relativeTo(source).invariantSeparatorsPath }
        out.bufferedWriter(Charsets.UTF_8).use { w ->
            w.write("// GENERATED FILE — do not edit. Source: kit-setup/templates/\n")
            w.write("// Regenerated by Gradle task `generateEmbeddedTemplates` on every build.\n\n")
            w.write("package com.aikit.setup.embedded\n\n")
            w.write("/**\n")
            w.write(" * All files staged under `kit-setup/templates/` baked into the binary.\n")
            w.write(" * Keys are repo-relative paths using forward slashes (e.g. `kit/_shared/agents/Main.body.md.template`).\n")
            w.write(" * Values are the file contents as UTF-8 strings.\n")
            w.write(" */\n")
            w.write("object EmbeddedTemplates {\n")
            w.write("    val files: Map<String, String> = buildMap {\n")
            files.forEach { f ->
                val rel = f.relativeTo(source).invariantSeparatorsPath
                val content = f.readText(Charsets.UTF_8)
                w.write("        put(\n")
                w.write("            \"${escapeKotlin(rel)}\",\n")
                w.write("            ")
                w.write(emitStringLiteral(content))
                w.write(",\n")
                w.write("        )\n")
            }
            w.write("    }\n")
            w.write("}\n")
        }
    }
}

fun escapeKotlin(s: String): String =
    s.replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\$", "\\\$")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")

// Use raw triple-quoted strings to keep generated source compact, but we have
// to escape any literal `"""` and any `${...}` interpolations defensively.
fun emitStringLiteral(content: String): String {
    val sanitized = content
        .replace("\$", "\${'$'}")
        .replace("\"\"\"", "\"\"\${'\"'}")
    return "\"\"\"" + sanitized + "\"\"\""
}

kotlin {
    mingwX64("mingwX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    macosX64("macosX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    macosArm64("macosArm64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    linuxX64("linuxX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedSrcDir)
            dependencies {
                implementation(kotlin("stdlib"))
            }
        }
    }
}

// Make sure every Kotlin compile task sees the generated file.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateEmbeddedTemplates)
}
