import java.nio.file.Path

plugins {
    kotlin("multiplatform") version "2.1.20"
}

group = "com.aikit"
version = "2.0.0"

repositories {
    mavenCentral()
}

// ─────────────────────────────────────────────────────────────────────────────
// Template embedding
// ─────────────────────────────────────────────────────────────────────────────
// The CLI must work without runtime resource lookup (Kotlin/Native), so every
// file under templates/ is captured into a generated Kotlin source as string
// constants in a single Map. The result is a normal commonMain source the
// compiler folds into the binary.

val templatesSourceDir = layout.projectDirectory.dir("templates")
val templatesGenRoot = layout.buildDirectory.dir("generated/templates/kotlin")

val generateTemplates by tasks.registering {
    description = "Embeds templates/ files into a generated Templates.kt source."
    group = "build"

    val inputDir = templatesSourceDir
    val outputRoot = templatesGenRoot

    inputs.dir(inputDir).withPropertyName("templates").withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(outputRoot).withPropertyName("templatesOut")

    doLast {
        val baseDir: Path = inputDir.asFile.toPath()
        val files = inputDir.asFileTree.matching { include("**/*") }.files
            .filter { it.isFile }
            .sortedBy { it.absolutePath }

        val pkgDir = outputRoot.get().asFile.resolve("com/aikit/setup/templates")
        pkgDir.mkdirs()
        val outFile = pkgDir.resolve("Templates.kt")

        val sb = StringBuilder()
        sb.appendLine("// Generated by :generateTemplates — do not edit.")
        sb.appendLine("package com.aikit.setup.templates")
        sb.appendLine()
        sb.appendLine("internal object Templates {")
        sb.appendLine("    val files: Map<String, String> = mapOf(")
        for (f in files) {
            val rel = baseDir.relativize(f.toPath()).toString().replace('\\', '/')
            val content = f.readText(Charsets.UTF_8)
            sb.append("        ")
            sb.append(escapeKotlinStringLiteral(rel))
            sb.append(" to ")
            sb.append(emitChunkedKotlinString(content))
            sb.appendLine(",")
        }
        sb.appendLine("    )")
        sb.appendLine("}")
        outFile.writeText(sb.toString(), Charsets.UTF_8)
    }
}

kotlin {
    mingwX64("mingwX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    macosX64("macosX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    macosArm64("macosArm64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }
    linuxX64("linuxX64") {
        binaries {
            executable {
                entryPoint = "com.aikit.setup.main"
                baseName = "kit-setup"
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(templatesGenRoot)
            dependencies {
                implementation(kotlin("stdlib"))
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateTemplates)
}

// ── helpers ──────────────────────────────────────────────────────────────────

fun escapeKotlinStringLiteral(s: String): String {
    val sb = StringBuilder(s.length + 2)
    sb.append('"')
    appendEscapedKotlin(sb, s)
    sb.append('"')
    return sb.toString()
}

/**
 * Emits [content] as a Kotlin expression that produces the original string at
 * compile time. Long strings are split into ~1000-char chunks joined with `+`
 * so we don't rely on any single literal being short enough for the compiler.
 */
fun emitChunkedKotlinString(content: String): String {
    if (content.isEmpty()) return "\"\""
    val chunkSize = 1000
    val sb = StringBuilder()
    var i = 0
    var first = true
    while (i < content.length) {
        val end = (i + chunkSize).coerceAtMost(content.length)
        val piece = content.substring(i, end)
        if (!first) sb.append(" + ")
        sb.append(escapeKotlinStringLiteral(piece))
        first = false
        i = end
    }
    return sb.toString()
}

fun appendEscapedKotlin(sb: StringBuilder, s: String) {
    for (c in s) {
        when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            '$' -> sb.append("\\$")
            else -> if (c.code < 0x20) {
                sb.append("\\u")
                val hex = c.code.toString(16)
                repeat(4 - hex.length) { sb.append('0') }
                sb.append(hex)
            } else {
                sb.append(c)
            }
        }
    }
}
